apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: thehive-gateway
  namespace: thehive
spec:
  gatewayClassName: envoy-gateway-class 
  listeners:
    - name: http
    protocol: HTTP
    port: 80
