apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: thehive-httproute
  namespace: thehive
spec:
  parentRefs:
  - name: thehive-gateway
  rules:
    - matches:
      - path:
        type: PathPrefix
          value: /
      backendRefs:
        - name: thehive-service
          port: 8001
