apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:odUEykIG5oJUP8QE78wLNxPc2zDEVDuWt1jfQ3skWfdaWaqAkUBVgeRSrf/d/0KQrJOvruvG5a5zrde4L7kztz6j5yAJidL4hLzSU7pvQ9tmvOHmJrmFuf5rJY41QEpjq9ggnaN9zOTaC6DBOydEdDrYDLhTol6k6A0S/7e+qPXpLowlzo4246dM6sIgeQbH6fLE5oYOG/2RblRXH1MKeB/0jCbLJJ1VUONgn4VPptoIBmq0o4aGR5n18TZtSwKi248Qj8K4WIBOATatMgrU4V22uuOAExz/bY2C7Krtr2mCb5j0o9b+egHoEiU=,iv:hbHZT5ftX4/P5fhSPejqAE/l2y2qTA/IsTYiQpFL91w=,tag:h5i6cOkg32VhibVPgNnaLQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1cgdjmwj38stsrp9zq42d3xe7hlqll45fuxccwpur6vx5yxdfwsrqddlj8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MWh5QlhseEhybE03aGRK
            SWkrQWNiZzZLeS8yNDNGL2FLbGVGaTRTclhnCmlYVTZ6aGYyck5hUEkxTXZrVWwy
            OGhoY28yYjk5OHR3YmU2VFBWWjRZdHMKLS0tIHFqZ3VaeXZRak9OWVVSRWVqdzlK
            Z3Z6akJhMmw1aDUzc2g3WE95SmVlVlkKY3qlOyxwfKnneKkdlHjCCOTQ97MdgoxS
            +Mp3IDD/+aoYOYwka6FPgN7ig20uN+NtonvDYxlBXRDPKwlZ9bzWAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T13:16:00Z"
    mac: ENC[AES256_GCM,data:M98VDaT3idt2AP1nnTHxhzQLYiRHPz99QQFkUj67AnPMeujJA9rNXBCg9AQAHHsLP0Weihjw/Vj92X47i75WrhlSndjKsmGZu+cEJoF+cqEZ5Zx0Ennvuzxw5MQJ7DwQtMsG9B7c9y99CppxSEQo8jsY0JK9Y7+1UtNDSO/WATA=,iv:/wAo2VL67sHaVEVXc142Fj2QFDPJjFN+n1GpIIRa7dM=,tag:lkv4SDt7MoSms4RuOG2F/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
