apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LI/kIANIIkt1LQ+LjuAUXISPmdV+EeFqapp0LP50LLot7cg5NzU8Ek+JasRMVFR42+7NVTp58gM1euG/lcfEqoD1Z9A4dIL+BdNIE9merFHUpyqhMLAGiZc4XFLfXWDF2vGSpy1VbkGWYQWZeFww2vWnHcPx86j80lBfifV+S6tOlG2HntyQlaHMs6fiyUllgepyaVjvkkLUBAJN6cj8nHU0kUPRM+1tQn8PsKr/SvM8xe02YN+4yDZosDMhGgokWMBPd/9T3tg2BfdwPxdn7CiYbCxVrX/zPYMvmF8oVMVqR/tVNp3fkG91/SI=,iv:hENkwLQuZoJik+k9oRc4O1SexcLcc/EfQvL+5/izRDU=,tag:P8myPtGMbyz66CoN/b5tNw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1jl3w74lz2u053rwa39vus8kpjfjqm04f5zpls5mgek26ecmsva5q6dx60t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcXF5YUYrOGowKytvSmkz
            ckFRd0R0K2lJcnIweU5FZ25oTHNKSm1CSlNFClE2TkFVaUh0VHFUWUdiUHk3UUlB
            R1dRMzlTTU1tSHUyMjRuRElJZWdFRTAKLS0tIG5aZ0pGZFFwazk2RkU3dlZMTnZP
            Y2Q2ZWhRMG11OEY2WnM5S0E3UkI3MWMK+KjVUbmJYrHQS0i9Hk1o+SJDE9d/8cHL
            pj9Xh/j/58VE0A50tiXz5ogAdA2tC2tEgVQTz90tcMgjcUh7G3hjug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T11:36:39Z"
    mac: ENC[AES256_GCM,data:P1uohwmE+mKntZBvXN4EqwNiKXPVSRquwVSlHuMRJja9OApzOjCG/ueK/jGCOtMkVlRRwoD2w4a/nf91/KpNp5ieVU75ESllK58P7/GwbMhI2ctTE1l2f59/Q34RP7QhWWLP4qfpG0ncDpcHtujGJ73ZRNp+S9yBuXhPzBBSq14=,iv:UMfwKmqV3qbeJG6boGGckJ2IykispvsgprhbYKwUkWQ=,tag:eGtyOx7xON0FyFVZJ12nAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
