apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:CVlaJRfhye4=,iv:oXQUaPKvA6o4lMAHl7kQ03VXr58k5MmU0C/3LyhLk5o=,tag:stHMVTN0E6RSl1tLWGGNjg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:9U1BAH0yQd2evL+7,iv:UD6A4n86wu7rS/Jyxog2gDhcbDtGaQdMfkIrk8sS8Mc=,tag:NmMsPZ4g6IRP4fpA23qHNg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1jl3w74lz2u053rwa39vus8kpjfjqm04f5zpls5mgek26ecmsva5q6dx60t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QVJhbjdKSDh0WFk4RXBi
            RDg5MHFrRHA2Vmcxdk5nMGlrYmwzdDdzR0Y4CnB5QmQwZ0hIYi9jK1VWNzIrT1cx
            Zkc2WG1sMFZkK0owU0FwVGNpYUVBU28KLS0tIEhnSy9nY29Vcmc0M3JiWjZRaEJJ
            Tmo1VXJldzhMWitKdjloTlhiYmZyK1EKBLN8NkhvItYG25koDvNvfXELuhxoFmCa
            +1EkszakMyCBHgKS580czawI6wFOFyz5ZfcUHQ1e/eT/cN358jfvGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T11:44:26Z"
    mac: ENC[AES256_GCM,data:iogDlRxXaGYhaUMkQY9PY1X8zJ45MfJlGgjkgtp6lyuY4cYikTZGHlgYpUfwq3kc3Tach2xCqSUTCJJMs2HE/3A2/OHd+H+W3SAp18IZwd782nEcaiU9N1R1FQArqsG4JAOticz83VRCCwwQBy3Ay9jxhHmsr7m4npNl8gQPHeg=,iv:KNSRhCJHq+nJ+BKTeq6vLPdwMVaUk6sIJxtkzzb9sDw=,tag:8nLlt9q+VyonY3eUYvAsbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
