apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Qkl6SQ==,iv:jBOjPtVZQK6Prf2FVKhVpI7cEyk44bjOBX8pP1oSEq8=,tag:S+P/g2g21oQ8fLdp8OuLpQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:zTeh+p0jOEylJNv9,iv:fnPEHVRpCe7iMGLC1ZC6GZEt6gP0aPgIgOZx6Z8Tb1E=,tag:MrCTMZcNZmW3voWu5qfgQw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1cgdjmwj38stsrp9zq42d3xe7hlqll45fuxccwpur6vx5yxdfwsrqddlj8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU1JIeVVONElhRmdVQlNx
            cUFyQ3BOQVNXN0h4NnNLVm1lK1hWQ0pnc2pFCmlKS3JpM2poejZmdklGV1hYNklu
            OGdkRHU0K3BCdDhQbEI5aEQxbXdxRFEKLS0tIGZGVXFldThoakRmLy9Od3NxSDZh
            ZEJYV0FlNitxRFN3WWpZSERJYUNnL3cKvcNGKObEotHMUsGNrTJAYZVnSucniFdm
            axgQ0rQfrpi05T0QkSqq0oKOXoJd7vvBwupQG8szDn9pXAA6CoSzfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T13:16:49Z"
    mac: ENC[AES256_GCM,data:E/aFJgiVk2DY9YuIRToYsnTctPse5I+qZ/nhTiGK0OQvWza59w9tOMGLfjN3p1wFDUvkpODp1NMXvofjxLH5XoiInJgfArriHxN83iIBUmO/XkZxuQdiU4jrlj/QY3QrS12hDpZ5K9LYDCl7HUuHYm1rOZQKtwpNY9aJVcl0wno=,iv:cegF9jWw/lqvwNblAD8OTXcRmPcYEkBdJIL3EOVwimA=,tag:ey+hv7UaEM7Iw5Rk9+5WIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
