apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:xHa2+w==,iv:O5mb6AyGtdIavR1M8YRFUt5VDR1ab2dGolD2f+AoQNQ=,tag:C67SMVqp18SI4wajva5e/Q==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:3nKfRJ0FU2dujLu7,iv:rWKk4ALrQcf3WJfRMoIkVQq0RCTP1IZvCY3LZ0c0qDA=,tag:z9UyhWuE9A23D09T6EXYVA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1jl3w74lz2u053rwa39vus8kpjfjqm04f5zpls5mgek26ecmsva5q6dx60t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbU5sTXczck9Valc5Yit1
            RTFzeXdPanV1a2N0VHFYWm9RZkFNaGk2cWlvCkpKNlFVNWE0RU9RQjliS0J5V05W
            TmlGZW9tS0tMcXpjVGQ2SE1GOVFFWWcKLS0tIC9TNTdCN1RUV3F3ZW53QzBCVXU4
            Q1FyUnpmOUZ2MHJTYUtDT1VEM2dWUzAKT2uWjZxGCMwLYG4CAmN5z+Iv1a+g6Flq
            kXXUmjglAp2rhE6nvfftz9zcuRMdzYCAeqbODv86YnRPSVgSdkTRnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T11:47:09Z"
    mac: ENC[AES256_GCM,data:ryqSRzGzm80Nn+eKgwcQcIXBODPX8IobR5MqEF5w5OXQiBbW294GnvJkNSNgnKrzZ6UMbiKuC3eGEyIlfEVtwfAl49NM/M9JT8zw3mo+m7ksjpSlrKAveOobSQvdQNGbY8MgSOSMug+zLlRUszJwbpEEqSTVC6IMxkW9aBjNjoo=,iv:oRnttFfr+KZ3+fy8lonc/GpKNr3qC6+2ch+0DgISBIk=,tag:6xQe4/pDtyQAYLA8uKsyKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
