apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:H7mXN+IKw8X4v0TShvpWhIdjyxBhkfJtFPV0rklplHgExzH2DEYQv3rWVcJ0002D4W6X3Q7B62cxvRfoiqjR7wGB3v6OG3HCnCPgrDMpL8XldpXb3Whcd+2btYZYkgCaEfqa69AzlTBis6CHq9POOgmMX9sHj+N98AUyNNNmiRf7WMlSVT3VlHR/9skzZI1ubKvqaQjzrDaneS/4NHBkQWFPWblCKRUqn8E+nSwqyQn4n1Yjjy24eCqXBnHST1ICE43anycdPCbtxRoG+b8zweMfvoffuMTGUgD8vBpBagzTIgQ6MdXvck7zKGs=,iv:xMCvuu/ZjwcIr4FcjSgq64JnGx1UbxoOMO8qLxjUthw=,tag:KPQOPfVbe1yWxnK3zL4vNw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - recipient: age1kj5f7vuqcrm4kk0j5ux48k30apy0azzgzsdevh5y9zy9fdsyndnqjrqrac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSEptMzM2ajV6UmF2THF3
            aG9DSjFybkgrblNkQnRQMFhkRW55OUYzWWwwCitYU3pGeDUzUUE3QWRkeGtQd2Z3
            MER1YWMyaHhma1ZDTFUwMFVwMHpZVU0KLS0tIHpEaDBYMkVMaEJSME1sUkcvbUk5
            R0ZiSnV3T2ZQWmxIbUhPaHFUdEFodTQK9/vU8UjdCI/ZIecJYl7Q3nhzJI/hb9MN
            R5jnj/qjQrc3bA2pZ5ChwCN4az0TIGWY9uF2whUPEoL+F+UIlfmSDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-07T20:20:22Z"
    mac: ENC[AES256_GCM,data:HGf5SutmN9g3SIx7l1yiwFXsj71Aa9CqXXB77P0Dg27Wu5dxvFqBx6JERpVt+T2f9g95ReKGz9f0ZxN2hnw13w9+vIiYzn80BlD46LnX6Fw3HSJyImQBIVlcLq5FOMS28AaQauwlpX8itQX0jQ3usytf5UO9GNKyMMQ7VbsWzkA=,iv:OUo62tivJ6hZKpRBgrjMjCm3p2UlrVS0Nqd2wDehguw=,tag:LUwlQxhOZtDroyQnXyxEBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
