apiVersion: v1
kind: Service
metadata:
  name: thehive-service
  namespace: thehive
spec:
  type: LoadBalancer
  selector:
    app: thehive
  ports:
    - name: http-web
      port: 8001
      targetPort: 8000
