apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:    
      securitsContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - name: linkding
        image: sissbruecker/linkding:1.31.0
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: linkding-data
            mountPath: /etc/linkding/data
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
