apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:    
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          command: ["/bin/sh", "-c"]
          args: 
            - linkding python manage.py createsuperuser --username=admin --email=admin@behrlevi.org
          env:
            # Linkding will create this user automatically on first boot
            - name: LD_SUPERUSER_NAME
              value: "admin"
            - name: LD_SUPERUSER_PASSWORD
              value: "password"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
