apiVersion: v1
kind: Service
metadata:
    labels:
      app: linkding
    name: linkding
    namespace: linkding
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
  selector:
    app: linkding
  type: LoadBalancer
