apiVersion: v1
kind: Service
metadata:
    labels:
      app: linkding
    name: linkding
    namespace: linkding
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 8080
    selector:
      app: linkding
    type: LoadBalancer
