apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
  namespace: renovate
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "Foltozó Robot <renovate@behrlevi.org>"
  RENOVATE_PLATFORM: "github"