apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Kvj1fN5sjCPPyZ0yvnyhTFa8EfHvjz0uvA0PGLeqENF+vtU/I3Oq2M19+taLbCbDdx0MAo48CpQ=,iv:nKKGkE6PHqwLAqUlDlPDPfZ4eu2TJqoQRWA4ueSTO/g=,tag:2SSqpItl6gOO/8aUWxsfKQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1jl3w74lz2u053rwa39vus8kpjfjqm04f5zpls5mgek26ecmsva5q6dx60t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhckRyanlXRkJOVFh2K2Zo
            Mi9STkIzTVB1M3dsb1ZodXFqaXdUNEcxMkZjCmRwV2ZaS0pvMlorUlgvdm81anZl
            bmdwUERLTVJMQjNJKzd6cTdiMzdPNjAKLS0tIGVFcU00MngzYzBtWWd5Znk5VXdV
            dWNuWkZpcVIyVkp4UGMvVFhUZ1F2d00KMG2ZzNKYricRH+NhcWjJoKdTrf71Wzxf
            JQHbFvIXHUq8y6WzwxUM54rDKKH8v2KzHoY5QwAysW3aNIfNa+B7GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T12:32:19Z"
    mac: ENC[AES256_GCM,data:kj5Fdhhpax09Q4H7QDMQK5xamxawcyzkxfxxn5c4VCQ0tyPyyrb0R2Zjr3F34fjF6D/D8Eka1/PUhAnibg5dtE39jhE0Z4u5IykWIpInCiJZCC5i6eUtFLbWnus7qGjiICr8ciCXC1F1yycbPcs9rBLv1CRWWcgJ0vKXYLcBjrg=,iv:gqVxwdzrVR8au4h9wi9TjI0Ob11cOIa3WMcfiGMT56Q=,tag:6HyfZc8Dznn2R7xKV98kjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
