apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:lFEt/p/YVJ4Abt1CSkO5yQNHyjM4pym2cAfeQrlSpkXbMKUb9UFvXXo+rLd8CJlPDFYiXLVqoUs=,iv:23SeJW34Dx+PY6n0WpstKGxXLsfLmJLYvRTyIBhIr5A=,tag:CNcw01hL4eit40XA/wW+Cw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1cgdjmwj38stsrp9zq42d3xe7hlqll45fuxccwpur6vx5yxdfwsrqddlj8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbG0wWlBVQzNXSFkvbnlm
            cHozTXdiMTNXcWR5NVVIbjZMV21ramdJTW1vCnByTlZtT0E4U0dmK1VvVURvTFVr
            UnlZUjROYUVjMXNlZTRrNTV0ekdHWTgKLS0tIHdsQ01KYW9nNHdNN1BocWxTbmRx
            Z1ltazg0TTBKUUhTN3I0R0tKcFYvdlEKWEFtZsMJBmGyV0Rw6Mj0h7Xf6/PWEFEQ
            fR5k+0IGxPZMJMQ5XpzlCLfSK8JbO0/Du/jAcqMiVK9QOkRckHTLmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T13:13:48Z"
    mac: ENC[AES256_GCM,data:NL4hErwnVjBDkpp4tlsN+PMj5GBE4TqM6/dat9jkJKFbprQgxIGcs4PZuoAccKFlpVjh4AHcjcRAt/C3vBQwKfs29l2bbHBFDah4knzX0qOcmrE6bTBoLVUnGFrtoXFP9evKWNuy7e4rVtBQdGhcV6uAe9NpHuhfBNJ4emfsbd4=,iv:5dgp5DQ3U+Oj6aXGyzzyLLn+khAobYCk+LQ+4/fNZ98=,tag:1gvPcH+zCYqt+1MC5doC9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
